spring:
  application:
    name: ${APP_NAME:purchase}

  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/purchases}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}

app:
  exchange:
    base-url: ${EXCHANGE_API_URL:https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/rates_of_exchange}
    page-size: ${EXCHANGE_PAGE_SIZE:100}
    max-months: ${EXCHANGE_MAX_MONTHS:6}
    max-iterations: ${EXCHANGE_MAX_ITERATIONS:100} # Safety Limit - to prevent infinite loops in case of API issues

  rest-client:
    connect-timeout: ${REST_CLIENT_CONNECT_TIMEOUT:5000}    # Connection timeout in milliseconds (5 seconds)
    read-timeout: ${REST_CLIENT_READ_TIMEOUT:10000}         # Read timeout in milliseconds (10 seconds)


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

